### ISSUE TITLE
Lighter UI-less container

### ISSUE THREAD

**Issue by Daniel15** [groenator/iptvboss-docker#23] opened 2024-05-10 17:15 UTC
It would be useful to have a second version of the container that's lighter weight and doesn't contain any UI libraries or VNC, for people that just want to use the Docker container for the cronjob in `-noGui` mode.

**Comment by groenator** [comment] 2024-05-10 19:03
Hi,

Currently, that's not possible. You need to raise this with the developer. 

Once boss is running as a web server, I would definitely build one.

Regards,

**Comment by Daniel15** [comment] 2024-05-10 19:09
I haven't tried with the newer versions of IPTVBoss (haven't used it in a few years), but this was doable with the old version. As long as you have the JRE installed, you could run IPTVBoss in noGui mode without a UI and it'd work fine even if you don't have any UI libraries installed. I'll try it on my headless Raspberry Pi and see. 

My use case is editing the config on my computer and only using a Docker container for the cronjob.

**Comment by groenator** [comment] 2024-05-10 19:22
How would you edit/add playlist? Edit logos and so many other things?

**Comment by Daniel15** [comment] 2024-05-10 20:01
> How would you edit/add playlist? Edit logos and so many other things?

No editing... Just the cronjob that updates the playlist and XMLTV files. I'd do editing on my computer rather than using the Docker container. The Docker would only be for the cronjob.

**Comment by groenator** [comment] 2024-05-10 20:12
This is not a bad idea. However, I've seen users preferring having one instance of boss and then use a browser to open the app and use it. I also prefer this way. 

When I have time I will look to create an image without GUI/VNC. 

I will leave this feature request opened and add it on my list. 

Regards,

**Comment by mdezzi** [comment] 2024-05-12 20:06
@groenator This seems to be working great. I noticed that the CRONJOB env automatically drops a line in the CRONTAB file to run the nogui on that schedule. However, I am currently running my nogui a few times per day, (0:00, 6:00, 8:00, 12:00, 18:00). I can manually update the cron file in the container, but i assume this would be overwritten if the image is pulled again. Any ideas on getting multiple cron lines to persist?

**Comment by groenator** [comment] 2024-05-12 20:43
Hi,

Have you checked the docs? When you set the CRON_SCHEDULE env with your own schedule it will automatically set inside the crontab. 

Lets sau you want to run the cron every 6h, all you need is write a cron schedule that run's every 6h and add it into the CRON_SCHEDULE env. 

Are you using a docker-compose file for your set up?

Regards,

**Comment by mdezzi** [comment] 2024-05-12 20:52
Yes, I set the CRON_SCHEDULE environment variable, and i see that it updated the cron in the container. 

I am on an Unraid system and I am currently using a docker container that is nogui only. When the container starts it runs the nogui script and then shuts down. So in my host cron i have the following: 

```
0 0 * * * docker start iptvboss
0 6 * * * docker start iptvboss
0 8 * * * docker start iptvboss
0 12 * * * docker start iptvboss
0 18 * * * docker start iptvboss
```

It's not exactly 6 hour intervals (because my provider updates at random times during the day), but i dont think you could write that configuration in a single cron line (which is why i have 5). Any ideas?

**Comment by groenator** [comment] 2024-05-12 20:53
Yes, you can. When you want to run your cron? Every 6h?

**Comment by groenator** [comment] 2024-05-12 20:58
This is an example of a cron running every 6h.
0 */6 * * *

**Comment by mdezzi** [comment] 2024-05-12 20:59
That config is not every 6 hours (because of the 08:00), but I was able to figure it out from a cron generator: 

`0 0,6,8,12,18 * * *`

Thanks!

**Comment by groenator** [comment] 2024-05-12 21:00
This is another example of a cron running every 12h at 04:00am and 17:00pm in the afternoon. 
`0 04-17/12 * * *`
You can create a cron to run every 6h at your preferable time.

**Comment by groenator** [comment] 2024-05-13 16:24
Btw, can I close this request? Are you happy with the container?

**Comment by mdezzi** [comment] 2024-05-13 16:35
I'm all good, but I didn't create the issue, I was just piggybacking on the one already created.

I confirmed my cron is working as expected and the cronitor functionality is very nice as well.

**Comment by groenator** [comment] 2024-05-13 19:15
My bad, I meant request :)
I am glad to hear it's working well. I'll close this feature request. 

Regards,

**Closed by groenator** 2024-05-13 19:15 UTC

**Comment by Daniel15** [comment] 2024-05-13 20:34
The feature request hasn't actually been implemented yet though 🤔

**Comment by groenator** [comment] 2024-05-13 22:11
I added a task list in the readme. This should be enough for now.
